workflow

diff --git a/.github/workflows/test_suite.yml b/.github/workflows/test_suite.yml
--- a/.github/workflows/test_suite.yml
+++ b/.github/workflows/test_suite.yml
@@ -15,23 +15,26 @@ jobs:
     - name: PHP Version
       run: php -v
 
+#    - name: Install composer
+#      run: |
+#        EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+#        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+#        ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+#
+#        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+#        then
+#            >&2 echo 'ERROR: Invalid installer signature'
+#            rm composer-setup.php
+#            exit 1
+#        fi
+#
+#        php composer-setup.php --install-dir=/bin --filename=composer
+#        RESULT=$?
+#        rm composer-setup.php
+#        exit $RESULT
+
     - name: Install composer
-      run: |
-        EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
-        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-        ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
-
-        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
-        then
-            >&2 echo 'ERROR: Invalid installer signature'
-            rm composer-setup.php
-            exit 1
-        fi
-
-        php composer-setup.php --install-dir=/bin --filename=composer
-        RESULT=$?
-        rm composer-setup.php
-        exit $RESULT
+      uses: ./.github/actions/install_composer
 
     - name: Checkout
       uses: actions/checkout@v1
