workflow

diff --git a/.github/workflows/test_suite.yml b/.github/workflows/test_suite.yml
--- a/.github/workflows/test_suite.yml
+++ b/.github/workflows/test_suite.yml
@@ -16,7 +16,22 @@ jobs:
       run: php -v
 
     - name: Install composer
-      uses: ./.github/actions/composer_install.sh
+      run: |
+        EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+        then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+
+        php composer-setup.php --quiet
+        RESULT=$?
+        rm composer-setup.php
+        exit $RESULT
 
     - name: Checkout
       uses: actions/checkout@v1
